### ISSUE TITLE
[OPTIMIZATION] Windows 卸载成功状态判断逻辑优化

### ISSUE THREAD

**Issue by ZhuoZhuoCrayon** [TencentBlueKing/bk-nodeman#1345]
**你想要什么功能**

**为什么需要**

**建议如何实现**

* 判断 `bin` 目录下是否有文件，如果没有文件也认为是移除成功

**Comment by CohleRustW** [comment]
1. 无法移除文件的具体原因：`Directory removed Error: The process cannot access the file because it is being used by another process. (os error 32)`
2. 可能的解决方式(在之前的操作中不要在对应的目录打开`CMD`)
 ``That is not how it works, if a process has the file open, it will be locked.The solution is to figure out what process that is and how to alter it to not keep the file or dir open. For example if you have a file in an editor that keeps it open, exiting the editor will free the file, if you have a cmd open in a directory that you want to delete, you have to cd out of the dir.``
